[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

#[project]
#name = "witch-msa"
#dynamic = ["version"]
#
#[tool.setuptools.dynamic]
#version = {attr = "witch.__version__"}
